[default.extend-words]
VCS = "VCS"
RACI = "RACI"
Sharepoint = "Sharepoint"
ITSM = "ITSM"
Mellanox = "Mellanox"
Qlogic = "Qlogic"
Emulex = "Emulex"
CMDB = "CMDB"
locationCode = "locationCode"
DHC = "DHC"
customerCode = "customerCode"
CESDHC = "CESDHC"
avr = "avr"
bil = "bil"
hgw = "hgw"
hsv = "hsv"
ica = "ica"
nes = "nes"
pxy = "pxy"
srs = "srs"
tss = "tss"
wus = "wus"
prereqVM = "prereqVM"
rsce = "rsce"
platformAdministrators = "platformAdministrators"
OpsManager = "OpsManager"
DevSecOps = "DevSecOps"
NX = "NX"
mec = "mec"
vli = "vli"
vnc = "vnc"
kms = "kms"
sdm = "sdm"
esx = "esx"
bck = "bck"
importBlueprintCloudAssembly = "importBlueprintCloudAssembly"
vx = "vx"
lldHcx = "lldHcx"
lldSDDCVmwareCloudFoundation = "lldSDDCVmwareCloudFoundation"
lldSoftwareDefinedNetworks = "lldSoftwareDefinedNetworks"
cmp = "cmp"
mgmt = "mgmt"
VM = "VM"
DRAC = "DRAC"
Anthos = "Anthos"
CTX = "CTX"
DAC = "DAC"
DDR = "DDR"
ECC = "ECC"
LPE = "LPE"
Megaraid = "Megaraid"
NVMe = "NVMe"
SAS = "SAS"
SATA = "SATA"
SFP = "SFP"
iCare = "iCare"
VxRail = "VxRail"
SSDs = "SSDs"
ENT = "ENT"
ELA = "ELA"
KMIP = "KMIP"
PSC = "PSC"
OpenShift = "OpenShift"
Tanzu = "Tanzu"
vCloud = "vCloud"
DDI = "DDI"
TKG = "TKG"
FW = "FW"
HCL = "HCL"
BDS = "BDS"
Nessus = "Nessus"
GTS = "GTS"
CNT = "CNT"
NDCS = "NDCS"
HW = "HW"
Gbit = "Gbit"
Mbit = "Mbit"
Kbit = "Kbit"
ACL = "ACL"
OoB = "OoB"
iLO = "iLO"
PCI = "PCI"
HBA = "HBA"
XD = "XD"
Xeon = "Xeon"
PowerEdge = "PowerEdge"
ProSupport = "ProSupport"
OpenManage = "OpenManage"
DWPD = "DWPD"
RDIMM = "RDIMM"
Avamar = "Avamar"
EPYC = "EPYC"
Infoblox = "Infoblox"
pCPU = "pCPU"
MAIA = "MAIA"
WL = "WL"
SKUs = "SKUs"
SKU = "SKU"
Gbps = "Gbps"
Mbps = "Mbps"
Kbps = "Kbps"
bootable = "bootable"
hostname = "hostname"
OVF = "OVF"
CloudLink = "CloudLink"
vDS = "vDS"
vMotion = "vMotion"
NIC = "NIC"
HCX = "HCX"
BOM = "BOM"
Broadcom = "Broadcom"
LSI = "LSI"
EMC = "EMC"
iDRAC = "iDRAC"
NICs = "NICs"
VID = "VID"
SVID = "SVID"
SDID = "SDID"
WinSCP = "WinSCP"
JSON = "JSON"
async = "async"
vRSLCM = "vRSLCM"
Saacon = "Saacon"
SSRs = "SSRs"
dev = "dev"
SaaS = "SaaS"
vIDM = "vIDM"
ServiceNow = "ServiceNow"
IPAM = "IPAM"
VPZ = "VPZ"
VPZs = "VPZs"
dl = "dl"
ki = "ki"
DAS = "DAS"
GRE = "GRE"
IaaS = "IaaS"
VRO = "VRO"
API = "API"
APIs = "APIs"
UI = "UI"
GUI = "GUI"
subnet = "subnet"
subnets = "subnets"
uplink = "uplink"
uplinks = "uplinks"
namespace = "namespace"
balancer = "balancer"
balancers = "balancers"
vRealize = "vRealize"
Kubernetes = "Kubernetes"
Atos = "Atos"
VMware = "VMware"
CSI = "CSI"
SCP = "SCP"
TCP = "TCP"
UDP = "UDP"
SDDC = "SDDC"
HTTPS = "HTTPS"
NTP = "NTP"
BIL = "BIL"
DRS = "DRS"
UTF = "UTF"
vCPU = "vCPU"
CPU = "CPU"
VCF = "VCF"
SDK = "SDK"
vCenter = "vCenter"
SDKs = "SDKs"
PKS = "PKS"
vROPS = "vROPS"
ATLM = "ATLM"
CSV = "CSV"
ABX = "ABX"
NSX = "NSX"
Evanios = "Evanios"
Ansible = "Ansible"
HashiCorp = "HashiCorp"
WinRM = "WinRM"
WSUS = "WSUS"
sudo = "sudo"
sudoers = "sudoers"
AVN = "AVN"
LVM = "LVM"
LTS = "LTS"
RBAC = "RBAC"
SDN = "SDN"
LLD = "LLD"
LLDs = "LLDs"
HLD = "HLD"
HLDs = "HLDs"
TOS = "TOS"
VMFS = "VMFS"
vSAN = "vSAN"
VLAN = "VLAN"
syslog = "syslog"
vRLI = "vRLI"
LDAP = "LDAP"
SMB = "SMB"
UAC = "UAC"
UEFI = "UEFI"
WLAN = "WLAN"
TPM = "TPM"
NTLM = "NTLM"
IOMMU = "IOMMU"
CSE = "CSE"
Bitlocker = "Bitlocker"
AES = "AES"
SLA = "SLA"
SRM = "SRM"
DNS = "DNS"
CNA = "CNA"
CEB = "CEB"
AHS = "AHS"
ATF = "ATF"
TBD = "TBD"
FQDN = "FQDN"
vRA = "vRA"
onboarding = "onboarding"
onboarded = "onboarded"
VMs = "VMs"
IOPS = "IOPS"
RHEL = "RHEL"
SLES = "SLES"
PKI = "PKI"
ESXi = "ESXi"
SSO = "SSO"
SSL = "SSL"
Jira = "Jira"
vSphere = "vSphere"
McAfee = "McAfee"
Biometric = "Biometric"
SHA = "SHA"
TLS = "TLS"
SYSVOL = "SYSVOL"
IIS = "IIS"
GPO = "GPO"
GPOs = "GPOs"
Kerberos = "Kerberos"
KDC = "KDC"
RPC = "RPC"
SSD = "SSD"
CVE = "CVE"
RTO = "RTO"
FND = "FND"
ND = "ND"
Hashi = "Hashi"
