site_name: HomeLab Documentation

theme:
  name: material

nav:
  - Home: index.md
  - User Guide:
      - Overview: UserGuide/index.md
  - Design:
      - Overview: design/index.md
      - Design Template: design/hld-template
  - Work Instructions:
      - Overview: workInstructions/index.md
