name: 📖 Deploy GitHub Pages Using Hugo

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  create-pages:
    uses: jijeeshhomelab/Actions/.github/workflows/hugo-pages.yml@main
    secrets:
      GH_ACTIONS_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
    with:
      GH_BRANCH: ${{ github.ref_name }}
